package rules

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const GeneratedRulesetFilename = "000-generated-ruleset.yaml"

func SaveDir(dir string, rs Ruleset) error {
	rs = rs.Normalized()
	if _, err := ValidateRulesetReport(rs); err != nil {
		return err
	}

	parent := filepath.Dir(dir)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return err
	}

	tmpDir, err := os.MkdirTemp(parent, "."+filepath.Base(dir)+".tmp-")
	if err != nil {
		return err
	}
	cleanupTmp := true
	defer func() {
		if cleanupTmp {
			_ = os.RemoveAll(tmpDir)
		}
	}()

	data, err := marshalRulesetYAML(rs)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(tmpDir, GeneratedRulesetFilename), data, 0o644); err != nil {
		return err
	}

	backupDir := filepath.Join(parent, "."+filepath.Base(dir)+".bak")
	_ = os.RemoveAll(backupDir)

	originalExists := false
	if _, err := os.Stat(dir); err == nil {
		originalExists = true
		if err := os.Rename(dir, backupDir); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.Rename(tmpDir, dir); err != nil {
		if originalExists {
			_ = os.Rename(backupDir, dir)
		}
		return err
	}
	cleanupTmp = false

	if originalExists {
		if err := os.RemoveAll(backupDir); err != nil {
			return err
		}
	}

	return nil
}

func marshalRulesetYAML(rs Ruleset) ([]byte, error) {
	data, err := yaml.Marshal(rs)
	if err != nil {
		return nil, fmt.Errorf("marshal ruleset: %w", err)
	}

	header := []byte("# Generated by agctl save. Manual edits may be overwritten.\n")
	return append(header, data...), nil
}
