// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type agentguardianCommKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type agentguardianEvent struct {
	_      structs.HostLayout
	Pid    uint32
	Tid    uint32
	Action uint32
	Op     uint32
	Ret    int32
	Aux    uint32
	Comm   [16]int8
	Path   [64]int8
}

type agentguardianFdKey struct {
	_    structs.HostLayout
	Tgid uint32
	Fd   uint32
}

type agentguardianPendingOpen struct {
	_      structs.HostLayout
	Action uint8
	Pad    [3]uint8
	Path   [64]int8
}

type agentguardianPolicy struct {
	_          structs.HostLayout
	Action     uint8
	Pad        [3]uint8
	TargetPath [64]int8
	TextLen    uint32
	Find       [64]int8
	Replace    [64]int8
}

type agentguardianRewriteState struct {
	_            structs.HostLayout
	BufAddr      uint64
	BytesToScan  uint32
	Offset       uint32
	Replacements uint32
	_            [4]byte
}

type agentguardianSyscallCommKey struct {
	_         structs.HostLayout
	Comm      [16]int8
	SyscallNr uint32
}

type agentguardianSyscallPidKey struct {
	_         structs.HostLayout
	Pid       uint32
	SyscallNr uint32
}

type agentguardianSyscallRule struct {
	_         structs.HostLayout
	SyscallNr uint32
	Mode      uint32
}

// loadAgentguardian returns the embedded CollectionSpec for agentguardian.
func loadAgentguardian() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentguardianBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load agentguardian: %w", err)
	}

	return spec, err
}

// loadAgentguardianObjects loads agentguardian and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*agentguardianObjects
//	*agentguardianPrograms
//	*agentguardianMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAgentguardianObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAgentguardian()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// agentguardianSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentguardianSpecs struct {
	agentguardianProgramSpecs
	agentguardianMapSpecs
	agentguardianVariableSpecs
}

// agentguardianProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentguardianProgramSpecs struct {
	EnforceExecve       *ebpf.ProgramSpec `ebpf:"enforce_execve"`
	EnforceFileOpen     *ebpf.ProgramSpec `ebpf:"enforce_file_open"`
	HandleCloseEnter    *ebpf.ProgramSpec `ebpf:"handle_close_enter"`
	HandleCloseExit     *ebpf.ProgramSpec `ebpf:"handle_close_exit"`
	HandleExecveEnter   *ebpf.ProgramSpec `ebpf:"handle_execve_enter"`
	HandleExecveatEnter *ebpf.ProgramSpec `ebpf:"handle_execveat_enter"`
	HandleOpenat2Enter  *ebpf.ProgramSpec `ebpf:"handle_openat2_enter"`
	HandleOpenat2Exit   *ebpf.ProgramSpec `ebpf:"handle_openat2_exit"`
	HandleOpenatEnter   *ebpf.ProgramSpec `ebpf:"handle_openat_enter"`
	HandleOpenatExit    *ebpf.ProgramSpec `ebpf:"handle_openat_exit"`
	HandleRawSysEnter   *ebpf.ProgramSpec `ebpf:"handle_raw_sys_enter"`
	HandleReadEnter     *ebpf.ProgramSpec `ebpf:"handle_read_enter"`
	HandleReadExit      *ebpf.ProgramSpec `ebpf:"handle_read_exit"`
	ScanReadBuffer      *ebpf.ProgramSpec `ebpf:"scan_read_buffer"`
}

// agentguardianMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentguardianMapSpecs struct {
	ClosingFds       *ebpf.MapSpec `ebpf:"closing_fds"`
	CommPolicyMap    *ebpf.MapSpec `ebpf:"comm_policy_map"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	ExecPolicy       *ebpf.MapSpec `ebpf:"exec_policy"`
	MapBuffAddrs     *ebpf.MapSpec `ebpf:"map_buff_addrs"`
	MapFds           *ebpf.MapSpec `ebpf:"map_fds"`
	PendingOpens     *ebpf.MapSpec `ebpf:"pending_opens"`
	PolicyMap        *ebpf.MapSpec `ebpf:"policy_map"`
	RewriteStates    *ebpf.MapSpec `ebpf:"rewrite_states"`
	ScanProgArray    *ebpf.MapSpec `ebpf:"scan_prog_array"`
	SyscallCommRules *ebpf.MapSpec `ebpf:"syscall_comm_rules"`
	SyscallPidRules  *ebpf.MapSpec `ebpf:"syscall_pid_rules"`
	SyscallRules     *ebpf.MapSpec `ebpf:"syscall_rules"`
}

// agentguardianVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type agentguardianVariableSpecs struct {
	UnusedCommKey *ebpf.VariableSpec `ebpf:"unused_comm_key"`
	UnusedEvent   *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedPolicy  *ebpf.VariableSpec `ebpf:"unused_policy"`
}

// agentguardianObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAgentguardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentguardianObjects struct {
	agentguardianPrograms
	agentguardianMaps
	agentguardianVariables
}

func (o *agentguardianObjects) Close() error {
	return _AgentguardianClose(
		&o.agentguardianPrograms,
		&o.agentguardianMaps,
	)
}

// agentguardianMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAgentguardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentguardianMaps struct {
	ClosingFds       *ebpf.Map `ebpf:"closing_fds"`
	CommPolicyMap    *ebpf.Map `ebpf:"comm_policy_map"`
	Events           *ebpf.Map `ebpf:"events"`
	ExecPolicy       *ebpf.Map `ebpf:"exec_policy"`
	MapBuffAddrs     *ebpf.Map `ebpf:"map_buff_addrs"`
	MapFds           *ebpf.Map `ebpf:"map_fds"`
	PendingOpens     *ebpf.Map `ebpf:"pending_opens"`
	PolicyMap        *ebpf.Map `ebpf:"policy_map"`
	RewriteStates    *ebpf.Map `ebpf:"rewrite_states"`
	ScanProgArray    *ebpf.Map `ebpf:"scan_prog_array"`
	SyscallCommRules *ebpf.Map `ebpf:"syscall_comm_rules"`
	SyscallPidRules  *ebpf.Map `ebpf:"syscall_pid_rules"`
	SyscallRules     *ebpf.Map `ebpf:"syscall_rules"`
}

func (m *agentguardianMaps) Close() error {
	return _AgentguardianClose(
		m.ClosingFds,
		m.CommPolicyMap,
		m.Events,
		m.ExecPolicy,
		m.MapBuffAddrs,
		m.MapFds,
		m.PendingOpens,
		m.PolicyMap,
		m.RewriteStates,
		m.ScanProgArray,
		m.SyscallCommRules,
		m.SyscallPidRules,
		m.SyscallRules,
	)
}

// agentguardianVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAgentguardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentguardianVariables struct {
	UnusedCommKey *ebpf.Variable `ebpf:"unused_comm_key"`
	UnusedEvent   *ebpf.Variable `ebpf:"unused_event"`
	UnusedPolicy  *ebpf.Variable `ebpf:"unused_policy"`
}

// agentguardianPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAgentguardianObjects or ebpf.CollectionSpec.LoadAndAssign.
type agentguardianPrograms struct {
	EnforceExecve       *ebpf.Program `ebpf:"enforce_execve"`
	EnforceFileOpen     *ebpf.Program `ebpf:"enforce_file_open"`
	HandleCloseEnter    *ebpf.Program `ebpf:"handle_close_enter"`
	HandleCloseExit     *ebpf.Program `ebpf:"handle_close_exit"`
	HandleExecveEnter   *ebpf.Program `ebpf:"handle_execve_enter"`
	HandleExecveatEnter *ebpf.Program `ebpf:"handle_execveat_enter"`
	HandleOpenat2Enter  *ebpf.Program `ebpf:"handle_openat2_enter"`
	HandleOpenat2Exit   *ebpf.Program `ebpf:"handle_openat2_exit"`
	HandleOpenatEnter   *ebpf.Program `ebpf:"handle_openat_enter"`
	HandleOpenatExit    *ebpf.Program `ebpf:"handle_openat_exit"`
	HandleRawSysEnter   *ebpf.Program `ebpf:"handle_raw_sys_enter"`
	HandleReadEnter     *ebpf.Program `ebpf:"handle_read_enter"`
	HandleReadExit      *ebpf.Program `ebpf:"handle_read_exit"`
	ScanReadBuffer      *ebpf.Program `ebpf:"scan_read_buffer"`
}

func (p *agentguardianPrograms) Close() error {
	return _AgentguardianClose(
		p.EnforceExecve,
		p.EnforceFileOpen,
		p.HandleCloseEnter,
		p.HandleCloseExit,
		p.HandleExecveEnter,
		p.HandleExecveatEnter,
		p.HandleOpenat2Enter,
		p.HandleOpenat2Exit,
		p.HandleOpenatEnter,
		p.HandleOpenatExit,
		p.HandleRawSysEnter,
		p.HandleReadEnter,
		p.HandleReadExit,
		p.ScanReadBuffer,
	)
}

func _AgentguardianClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agentguardian_bpfeb.o
var _AgentguardianBytes []byte
